texture_egl: add missing header include
texture_egl uses TextureTestEgl class when ENABLE_TEXTURE_TEST_EGL, but,
texture_test_egl.h is not included, so, the build error
happens.

Potentially, texture_navi_render_egl.h may cause the same error, so, I
added the include to them.

```
/home/akiyama/work/flutter/ivi-homescreen/shell/textures/egl/texture_egl.cc: In member function ‘flutter::EncodableValue TextureEgl::Create(Engine*, int64_t, int32_t, int32_t, const std::map<flutter::EncodableValue, flutter::EncodableValue>*)’:
/home/akiyama/work/flutter/ivi-homescreen/shell/textures/egl/texture_egl.cc:34:46: error: ‘TextureTestEgl’ was not declared in this scope; did you mean ‘TextureEgl’?
   34 |       m_textures->push_back(std::make_unique<TextureTestEgl>(m_flutter_view));
      |                                              ^~~~~~~~~~~~~~
      |                                              TextureEgl
/home/akiyama/work/flutter/ivi-homescreen/shell/textures/egl/texture_egl.cc:34:76: error: no matching function for call to ‘make_unique<<expression error> >(FlutterView*&)’
   34 |       m_textures->push_back(std::make_unique<TextureTestEgl>(m_flutter_view));
      |                                                                            ^
In file included from /opt/arene/sdk/v8.2.0/ivi/sa81x5/sysroots/aarch64-arene-linux/usr/include/c++/9.3.0/memory:80,
                 from /home/akiyama/work/flutter/ivi-homescreen/shell/textures/egl/texture_egl.h:5,
                 from /home/akiyama/work/flutter/ivi-homescreen/shell/textures/egl/texture_egl.cc:2:
/opt/arene/sdk/v8.2.0/ivi/sa81x5/sysroots/aarch64-arene-linux/usr/include/c++/9.3.0/bits/unique_ptr.h:856:5: note: candidate: ‘template<class _Tp, class ... _Args> typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...)’
  856 |     make_unique(_Args&&... __args)
      |     ^~~~~~~~~~~
/opt/arene/sdk/v8.2.0/ivi/sa81x5/sysroots/aarch64-arene-linux/usr/include/c++/9.3.0/bits/unique_ptr.h:856:5: note:   template argument deduction/substitution failed:
/home/akiyama/work/flutter/ivi-homescreen/shell/textures/egl/texture_egl.cc:34:76: error: template argument 1 is invalid
   34 |       m_textures->push_back(std::make_unique<TextureTestEgl>(m_flutter_view));
      |                                                                            ^
In file included from /opt/arene/sdk/v8.2.0/ivi/sa81x5/sysroots/aarch64-arene-linux/usr/include/c++/9.3.0/memory:80,
                 from /home/akiyama/work/flutter/ivi-homescreen/shell/textures/egl/texture_egl.h:5,
                 from /home/akiyama/work/flutter/ivi-homescreen/shell/textures/egl/texture_egl.cc:2:
/opt/arene/sdk/v8.2.0/ivi/sa81x5/sysroots/aarch64-arene-linux/usr/include/c++/9.3.0/bits/unique_ptr.h:862:5: note: candidate: ‘template<class _Tp> typename std::_MakeUniq<_Tp>::__array std::make_unique(std::size_t)’
  862 |     make_unique(size_t __num)
      |     ^~~~~~~~~~~
/opt/arene/sdk/v8.2.0/ivi/sa81x5/sysroots/aarch64-arene-linux/usr/include/c++/9.3.0/bits/unique_ptr.h:862:5: note:   template argument deduction/substitution failed:
/home/akiyama/work/flutter/ivi-homescreen/shell/textures/egl/texture_egl.cc:34:76: error: template argument 1 is invalid
   34 |       m_textures->push_back(std::make_unique<TextureTestEgl>(m_flutter_view));
      |                                                                            ^
In file included from /opt/arene/sdk/v8.2.0/ivi/sa81x5/sysroots/aarch64-arene-linux/usr/include/c++/9.3.0/memory:80,
                 from /home/akiyama/work/flutter/ivi-homescreen/shell/textures/egl/texture_egl.h:5,
                 from /home/akiyama/work/flutter/ivi-homescreen/shell/textures/egl/texture_egl.cc:2:
/opt/arene/sdk/v8.2.0/ivi/sa81x5/sysroots/aarch64-arene-linux/usr/include/c++/9.3.0/bits/unique_ptr.h:868:5: note: candidate: ‘template<class _Tp, class ... _Args> typename std::_MakeUniq<_Tp>::__invalid_type std::make_unique(_Args&& ...)’ <deleted>
  868 |     make_unique(_Args&&...) = delete;
      |     ^~~~~~~~~~~
/opt/arene/sdk/v8.2.0/ivi/sa81x5/sysroots/aarch64-arene-linux/usr/include/c++/9.3.0/bits/unique_ptr.h:868:5: note:   template argument deduction/substitution failed:
/home/akiyama/work/flutter/ivi-homescreen/shell/textures/egl/texture_egl.cc:34:76: error: template argument 1 is invalid
   34 |       m_textures->push_back(std::make_unique<TextureTestEgl>(m_flutter_view));
      |                                                                            ^
/home/akiyama/work/flutter/ivi-homescreen/shell/textures/egl/texture_egl.cc: In member function ‘void TextureEgl::Dispose() const’:
/home/akiyama/work/flutter/ivi-homescreen/shell/textures/egl/texture_egl.cc:68:9: error: ‘TextureTestEgl’ has not been declared
   68 |         TextureTestEgl::Dispose(item.get(), static_cast<GLuint>(item->GetId()));
      |         ^~~~~~~~~~~~~~
/home/akiyama/work/flutter/ivi-homescreen/shell/textures/egl/texture_egl.cc: In member function ‘void TextureEgl::Draw() const’:
/home/akiyama/work/flutter/ivi-homescreen/shell/textures/egl/texture_egl.cc:90:9: error: ‘TextureTestEgl’ has not been declared
   90 |         TextureTestEgl::Draw(item.get());
      |         ^~~~~~~~~~~~~~
```

Signed-off-by: Kazuyoshi Akiyama <kazuyoshi.akiyama@woven-planet.global>