key_event: fix compile error about unordered_map
With using clang 10.1 in Yocto SDK, the following compile error is
caused.

```
/__w/ivi-homescreen/ivi-homescreen/shell/static_plugins/key_event/key_mapping.h:30:19: error: no template named 'unordered_map' in namespace 'std'
static const std::unordered_map<uint32_t, uint32_t> map_xkb_key_to_fl_snancode = {
             ~~~~~^
```

So, I fixed the included header from `<map>` to `<unordered_map>`.

Signed-off-by: Kazuyoshi Akiyama <kazuyoshi.akiyama@woven-planet.global>