fix building with crash handling enabled
Two fixes needed:
  - The space after "CRASH_HANDLER_RELEASE=" results in the following error:
    """
    ./constants.h:86:69: error: expected primary-expression before ‘;’ token
       86 | static constexpr char kCrashHandlerRelease[] = CRASH_HANDLER_RELEASE;
    """
    Remove the space

  - homescreen links against libunwind when BUILD_CRASH_HANDLER is set, however
    libunwind is not searched for when configuring. Use pkg_check_modules as
    libunwind does not install a .cmake file.